### ISSUE TITLE
Crashes after a few seconds every time since updating Roblox.

### ISSUE THREAD

**Issue by TeridaxXD001** [EmK530/BloxDump#10] opened 2024-10-28 07:32 UTC
This used to happen occasionally, but clearing the cache fixed it. That doesn't work anymore.
![Bloxdump Crash](https://github.com/user-attachments/assets/b09d73f8-4299-4664-8259-a27e409a42c4)

**Comment by EmK530** [comment] 2024-10-29 02:18
Thanks for the report, I'm trying to reproduce the issue but having a bit of trouble.
Do you have any details like steps to reproduce it or what game you were playing?
(this looks like an error from an avatar image? it would help to be sure and be able to encounter the issue myself for testing)

**Comment by EmK530** [comment] 2024-10-29 03:05
Let me know if [v5.1.2](https://github.com/EmK530/BloxDump/releases/tag/v5.1.2) solves any of the crashes you're encountering.
If it does then you can close the issue, if not then let me know and with some details to help me out.

**Comment by TeridaxXD001** [comment] 2024-10-30 04:10
v5.1.2 completed it smoothly. Since you asked, in every instance of crashing, including the earlier ones, the game was Sonic Speed Simulator, though this time, Really Easy Obby! was also in there.

**Comment by EmK530** [comment] 2024-10-30 09:37
Glad to hear it helped! If something is still crashing then go ahead reopen this issue.

**Comment by TeridaxXD001** [comment] 2024-12-06 04:52
It's back.
![bloxdump](https://github.com/user-attachments/assets/cbd17bdf-b2c8-4ab3-85ac-5a928764338a)

**Comment by EmK530** [comment] 2024-12-06 13:28
I'll try to investigate this, thanks

**Comment by EmK530** [comment] 2024-12-06 14:18
Noticed a mistake with file paths for srgb2lin and added some error catching, see if this is stable and report any issues!
[BloxDump-bugfixtest.zip](https://github.com/user-attachments/files/18039258/BloxDump-bugfixtest.zip)

**Comment by TeridaxXD001** [comment] 2024-12-07 05:14
Yes, worked like a charm, multiple times. Thank you!

**Closed** 2024-12-07 16:43 UTC
Labels: bug, good first issue
